# Copyright 2025 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM --platform=$BUILDPLATFORM quay.io/konveyor/builder:ubi9-latest AS kopia-builder

ARG BUILDPLATFORM
ARG TARGETOS
ARG TARGETARCH
ARG BUILDTAGS
ENV CGO_ENABLED=0
ENV GOPATH=/opt/app-root
ENV APP_ROOT=/opt/app-root
ENV BIN=kopia

WORKDIR $APP_ROOT/src/github.com/migtools/kopia

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -installsuffix "static" -tags "$BUILDTAGS" -o dist/$BIN ./

FROM fedora-toolbox:latest
RUN mkdir /.cache && chown 65534:65534 /.cache

# Install libguestfs and required tools
RUN dnf install -y \
    s3cmd \
    libguestfs \
    guestfs-tools \
    libguestfs-tools \
    libguestfs-xfs \
    fuse \
    qemu-img \
    qemu-kvm \
    mount \
    openssh-server \
    && dnf clean all
USER 65534:65534

COPY --from=kopia-builder /opt/app-root/src/github.com/migtools/kopia/dist/$BIN /
ENTRYPOINT ["/kopia"]

