apiVersion: v1
kind: Pod
metadata:
  name: kopia-vm-singlefile
  namespace: openshift-adp
  labels:
    app: kopia-vm-singlefile
spec:
  containers:
  - name: kopia
    image: quay.io/migtools/kopia:latest
    command: ["/bin/bash", "-c"]
    args: ["sleep infinity"]
    securityContext:
      runAsUser: 0 
      allowPrivilegeEscalation: false
  volumes:
  - name: cache-volume
    emptyDir: {}
  restartPolicy: Never
